### ISSUE TITLE
Controller name generation

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#180]
Example:
```
/api:
  /books:
    /chapters:
```

Please update controller name generation in a way to be able to have `ChapterBookController` as controller's interface name.
Currently it is only possible to have `BookChapterController` as interface name.

**Comment by kurtpa** [comment]
I think that having the name following the nesting order makes sense since the nested element is a subresource (ie since a chapter is part of a book, a Book Chapter implies "A Chapter in a Book" - whereas the opposite, ChapterBook implies some sort of Book owned by a Chapter which goes agains what this url is identifying imo

If this is implemented it should defintly be off by default

**Comment by piffta** [comment]
@kurtpa I completely agree with your comment, if you are looking at the example. I tried not to use real example from our implementation.

It would be nice to have default option (as is in current implementation) and new configuration option for generating controller interface name using reversed order.
