### ISSUE TITLE
Allow Generation of server contract without implementation

### ISSUE THREAD

**Issue by kurtpa** [phoenixnap/springmvc-raml-plugin#20]
The current generation engine is good for stubbing at project initiation, however keeping the plugin embedded in the project would overwrite the implementation if reused.

As such we would like to give configuration options on the type of code generation with the following options:

1. Controller Stubs (current functionality)
2. Controller Interface
3. Both (non-overwriting)
4. Delegate (being worked on in other fork)
5. ? Any other requests?

This would include an interface with the appropriate Spring annotations which can then be implemented by the controller implementation

```
public interface BooksResource {

@RequestMapping( ..... )
public List<Book> getBooks();

}


public class BooksController implements BooksResource {

@Override
public List<Book> getBooks() {
   // implementation
}
}
```

**Comment by aweisser** [comment]
Hi Kurt,

I just consolidated my work here: 
https://github.com/aweisser/springmvc-raml-plugin/tree/develop

Features implemented so far:
- Controller Stubs (current functionality mainly moved to Spring4ControllerSerializer class)
- Controller Interface (Spring4ControllerInterfaceWithAnnotationsSerializer)
- Delegate + Interface (Spring4DecoratorSerializer and Spring4ControllerInterfaceSerializer)
- User can now configure the generator class with a maven property (<ramlGenerator>).

What is most important: The RamlGenerator.generateClassForRaml(...) method now returns a list of Serializers each one generating a single artefact (like a class or an interface). 
We can now add and combine different serialization strategies.

Further features (implemented on the fly, because I need them for my own project): 
- Generators process the "required" attribute from .raml spec.
- Generators process "baseUri" attribute from .raml spec.
- User can overrule the "baseUri" attribute with a maven configuration property (<baseUri>).

I wrote some tests in springmvc-raml-parser module.

The solution is still not very clean. I'd like to see a JCodeModel solution instead of magic String concatenation inside the different Serializers. In addiationI'd like to refactor the whole code generation stuff into some Rule based style (just like org.jsonschema2pojo.rules.Rule).
But thats propably a task for the future I think. Small steps...

Could you please take a look at my work so far and give me some feedback!?

br,

Armin

**Comment by aweisser** [comment]
Forgot one additional feature:
- Generators now process the media type of the .raml spec.

**Comment by kurtpa** [comment]
Great work :)

I've been following your commits and I really like how you approached it.

I suggest we make a pull request into a feature branch and like that I can code review (sorry but this is pnap policy) and re integrate the code on master. Then we can continue building the features you suggested:
- using jcodemodel is on my to-do list already
- rules would be a great idea, especially since I need to support different spring versions (plus future proof it for 5.0) and I want to also generate non Java code (like clients or other contracts for migration)

Best regards

Kurt

Sent from Outlook<https://aka.ms/f818qx>



On Wed, Mar 16, 2016 at 12:03 AM -0700, "Armin Weißer" <notifications@github.com<mailto:notifications@github.com>> wrote:


Forgot one additional feature:

  *   Generators now process the media type of the .raml spec.

-

**Comment by kurtpa** [comment]
Hi Armin, 

First of all thanks again for taking the time to improve this project :) :). Could you please create a pull request from your develop to phoenixnap/master (if you are busy i can trigger this i think) - this will make it much easier for me to track the code review.

Thanks!
Kurt

**Comment by aweisser** [comment]
done

**Comment by kurtpa** [comment]
completed
