### ISSUE TITLE
generateUnreferencedSchema doesn't work for some cases

### ISSUE THREAD

**Issue by yuranos** [phoenixnap/springmvc-raml-plugin#203]
In my case I can't find a POJO generated for my exception scenarios. For example:

> ErrorDto: !include schemas/ErrorDto.raml
> ... 
> 500:
>             body:
>               application/json:
>                 type: ErrorDto`

ErrorDto is not generated.
@stojsavljevic , wht do you think about it? Am I missing something in config? I have:

`<generateUnreferencedSchemas>true</generateUnreferencedSchemas>`

**Comment by yuranos** [comment]
@stojsavljevic , can you help? Is it a proper bug or some limitation we can circumvent?

**Comment by yuranos** [comment]
@stojsavljevic , please assist.

**Comment by stojsavljevic** [comment]
Hi,

so there are few issues with this:
* property (`generateUnreferencedSchemas`) works only for schemas and not for data types since it will try to generate POJO using Jackson
* we're not supporting schemas with `1.0` since `RJP10V2RamlRoot` returns types in `getSchemas()` method

We can fix both issues but first one looks easy since we need to check raml version and generate POJOs same way we do that when type is actually used.

Please consider a PR :)

**Comment by yuranos** [comment]
@stojsavljevic, your activity on the 25th made me google Religion in Serbia, just to make sure you are not a crazy workaholic :stuck_out_tongue_closed_eyes:

**Comment by yuranos** [comment]
This ticket will be my next priority.
