### ISSUE TITLE
Problem with optional uriParameters

### ISSUE THREAD

**Issue by saraawss** [phoenixnap/springmvc-raml-plugin#215]
I am facing a problem, I have a raml file and I have to convert to spring java controller file.I added com.phoenixnap.oss pluging in pom file like this,

      <plugin>
  <groupId>com.phoenixnap.oss</groupId>
  <artifactId>springmvc-raml-plugin</artifactId>
  <version>0.10.11</version>
  <configuration>
    <ramlPath>src/main/resources/api.raml</ramlPath>
	<outputRelativePath>target/generated-sources</outputRelativePath>
    <addTimestampFolder>false</addTimestampFolder>
    <basePackage>de.adorsys.ramlspringboot.api</basePackage>
    <baseUri>/api</baseUri>
    <generateUnreferencedSchemas>true</generateUnreferencedSchemas>
	<generationConfig>
		<includeAdditionalProperties>false</includeAdditionalProperties>
	</generationConfig>
	<seperateMethodsByContentType>false</seperateMethodsByContentType>
	<rule>com.phoenixnap.oss.ramlapisync.generation.rules.Spring4ControllerStubRule</rule>
	<ruleConfiguration>			
	</ruleConfiguration>
  </configuration>
  <executions>
    <execution>
      <id>generate-springmvc-endpoints</id>
      <phase>compile</phase>
      <goals>
        <goal>generate-springmvc-endpoints</goal>
      </goals>
    </execution>
  </executions>
</plugin>

when I am generating java controller file generating like this,

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public Todo getTodoById(
        @PathVariable(required = false)
        Long id) {
        return null; 
    }

but @PathVariable(required = false) is getting error spring is not supporting required = false in @PathVariable.

Please advice me what should I do.

**Comment by aweisser** [comment]
It seems like a bug in one of the code generation strategies. The way to annotate an optional PathVariable in Spring is to use a Java8 Optional type refering to the following article: https://www.n-k.de/2016/05/optional-path-variables-with-spring-boot-rest-mvc.html

Workaround in your case:
Since you‘re using the StubRule you can simply repair the optional=false in the generated code. 

Please note: It‘s not a good practice to alter generated code at all. That‘s why we introduced other code generation rules like Spring4ControllerDecoratorRule or Spring4ControllerInterfaceRule. But in your case you decided to use the Spring4ControllerStubRule in which you have to inject your controller logic in the body of the generated controller method stub. So fixing the wrong required=false in the PathVariable is just another altering of the generated stub. ;)

But: it‘s still a bug.

**Comment by aweisser** [comment]
The affected rule is:

https://github.com/phoenixnap/springmvc-raml-plugin/blob/master/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/generation/rules/spring/SpringMethodParamsRule.java

**Comment by saraawss** [comment]
I tried to use Spring4ControllerDecoratorRule or Spring4ControllerInterfaceRule, but still it is generating @PathVariable(required = false).

How to repair the generated code?

**Comment by stojsavljevic** [comment]
@aweisser thnx for pointing out the solution (or let's call it a workaround).

@saraawss there is nothing you can to make your build passing until I implement the workaround.
But you can make the issue more clear and provide snippet of your raml :)
If I'm not mistaken, you have a raml like this:
```
/todos:
  /{todoId}:
    uriParameters: 
      todoId: 
        type: number
        required: false
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Todo
```
which leads to the code you pasted that is not supported by Spring although it compiles.

**Comment by stojsavljevic** [comment]
I'm going to push the fix soon although I'm not very happy with the solution/workaround.
The problematic part is multiple values for `@RequestMapping`.
With 1 optional param - there are 2 values, with 2 params - 4 values etc.
Bunch of mapping values might lead to unexpected mapping.
I added a warning in case of more than 1 optional uri param but I will still let a user to shoot himself in a leg if he wants to.
