### ISSUE TITLE
In Generated RAML we need to add change value "description".

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#23]
Hi kurtpa,
I am using spring MVC to RAML code. After generating RAML as per current implementation the value "description" in RAML is only method name. 
we need all comments of controller to description in RAML.

**Comment by kurtpa** [comment]
If the description of the controller is not being added this could be due to 2 reasons. Either the plugin is not able to read the source code (remember javadocs are not compiled into class files so we need the actual source files to be able to parse them)
Alternatively there are places in the chain where we will not have easy access to amend. For these cases there is the @description annotation that you can introduce in your code that can be appended by the plugin. If you paste a more specific code example i can give you more specific details

**Comment by rahulkamuni** [comment]
okay thanks for your suggestion.
Regarding first solution of adding java-docs. I have exported java docs from eclipse of my project and added in pom.xml But It is not working. After executing it printing console 
"Waring : Missing source for: "myClass" Java doc unavailable". How to add source. ?
Regarding second solution of adding custom annotation of "description".
As I need to annotate description in my controller class my question is JDK 1.8 require to execute my controller.

**Comment by kurtpa** [comment]
To add source you need to specify the search folder in the pom (see readme.MD for exact syntax and example)

Re jdk 8 you will only need it for generation.

**Comment by rahulkamuni** [comment]
OK thanks for reply. Let me try in my code.

**Comment by kurtpa** [comment]
Hi, If this is still an issue, kindly paste a code snippet or feature request. Alternatively i will close this issue

**Comment by rahulkamuni** [comment]
No issue you can close this issue.
Its worked for me. 
Thanks Kurtpa
