### ISSUE TITLE
generate-springmvc-endpoints failed

### ISSUE THREAD

**Issue by hamza-busuri** [phoenixnap/springmvc-raml-plugin#306]
When I follow the steps to run the app, I get the following build failure error. 

Execution generate-springmvc-controllers of goal com.phoenixnap.oss:springmvc-raml-plugin:0.8.6:generate-springmvc-endpoints failed: A required class was missing while executing com.phoenixnap.oss:springmvc-raml-plugin:0.8.6:generate-springmvc-endpoints: javax/xml/bind/SchemaOutputResolver

Does anyone know how to resolve this?

**Comment by claytontabone** [comment]
This seems like you're using Java version 9+. Since the introduction of the Jigsaw module system Java has removed some functionality from Java. The good thing is that this functionality is available as dependencies in Maven Central. The dependencies that you seem to be missing are the following:
```xml
			<dependency>
				<groupId>jakarta.xml.bind</groupId>
				<artifactId>jakarta.xml.bind-api</artifactId>
			</dependency>
	
			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-runtime</artifactId>
			</dependency>
```

Make sure you have dependency management for these to manage the version and that you include these as dependencies to the springmvc-raml-plugin and not directly to your project.
