### ISSUE TITLE
Uri params are treat literaly during implementation check

### ISSUE THREAD

**Issue by tsarnowski** [phoenixnap/springmvc-raml-plugin#54]
My raml contains urli params like below:
homologations:
  /{commision}:
    uriParameters:
      commisionNumber:
        type: "string"
        pattern: "^[a-zA-Z0-9]+$"
    /{commisionDay}
By mistake I changes path variable from commisionDay to commisionDayString and then ActionExistenceChecker don`t chceck my actions because resources not match.

What do You thing, if uri params don`t should be read only as some resource instead of checking params names?

**Comment by tsarnowski** [comment]
Now i realized that, that behavior  breaks response body check too.

**Comment by kurtpa** [comment]
The name of that variable matching the raml is really irrelevant since at runtime it would be changed to the actual variable content.

I believe there is a case where we are just checking if one exists and then using that to recurse down the tree. i will check if that logic is being applied to style checks
