### ISSUE TITLE
[Raml to code] plural / singular object name

### ISSUE THREAD

**Issue by andrealgiudice** [phoenixnap/springmvc-raml-plugin#76]
I have this raml file:
#%RAML 0.8
title: My Automation Services
version: 0.0.1-SNAPSHOT
baseUri: /
/devices:
  /{deviceId}:
    uriParameters:
      deviceId:
        displayName: Device ID
        type: string
        description: Some device id
        required: true
        example: 123
    /console:
      get:

The  springmvc-raml-parser generates the classes:
DeviceController and DeviceControllerDecorator. (Singular).

If then I add at the same RAML file:

/device:
  /something:
    get:      

Those are not added to the DeviceController.

**Comment by kurtpa** [comment]
Due to the nature of the generation engine, specifically the way we are grouping actions by url this will be nontrivial to fix such that the DevicesController contains both /devices and /device.
I think this is a corner-case at best, however if there are other reports of this affecting users we can fix this by allowing the singularisation of resources to peek ahead and check that if both a singular and a plural of the same resource exist, the name will change. This should be a relatively easy way to mitigate this issue
